steps = {};

function CreateStep(x, y, zone, target, description, completeEvent, questId, npcMessage)
  local step = {};
  step.x = x;
  step.y = y;
  step.zone = zone;
  step.description = description;
  step.target = target;
  step.completeEvent = completeEvent;
  step.questId = questId;
  step.npcMessage = npcMessage;
  return step;
end

table.insert(steps, CreateStep(44.12, 38.05, "Orgrimmar", "Ebyssian", "Turn in and accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(44.12, 38.05, "Orgrimmar", "Ebyssian", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(44.12, 38.05, "Orgrimmar", "Naleidea Rivergleam", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(44.12, 38.05, "Orgrimmar", "Scalecommander Cindrethresh", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(38.60, 56.97, "Orgrimmar", "Pathfinder Tacha", "Talk", "UNIT_QUEST_LOG_CHANGED"));
table.insert(steps, CreateStep(71.41, 50.68, "Orgrimmar", "Cataloger Coralie", "Talk", "UNIT_QUEST_LOG_CHANGED"));
table.insert(steps, CreateStep(57.10, 54.11, "Orgrimmar", "Boss Magor", "Talk", "UNIT_QUEST_LOG_CHANGED"));
table.insert(steps, CreateStep(55.06, 89.60, "Orgrimmar", "Kodethi", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(55.86, 12.70, "Durotar", "Naleidea Rivergleam", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.86, 12.70, "Durotar", "Naleidea Rivergleam", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.86, 12.70, "Durotar", "Archmage Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(55.86, 12.70, "Durotar", "Ebyssian", "Accept quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.86, 12.70, "Durotar", "Naleidea Rivergleam", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(55.06, 89.60, "Durotar", nil, "Board ship to Dragon Isles...", "QUEST_WATCH_UPDATE", 65444));
table.insert(steps, CreateStep(80.63, 27.67, "The Waking Shores", "Naleidea Rivergleam", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(80.63, 27.67, "The Waking Shores", "Naleidea Rivergleam", "Accept Quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(80.63, 27.67, "The Waking Shores", "Scalecommander Cindrethresh", "Accept Quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(80.63, 27.67, "The Waking Shores", "Boss Magor", "Accept Quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(80.32, 26.32, "The Waking Shores", "Protodragon Rib Cage", "Click on the Rib Cage. Kill and loot Dragons", "QUEST_WATCH_UPDATE", 65452));
table.insert(steps, CreateStep(78.80, 24.46, "The Waking Shores", "Archivist Spearblossom", "Rescue Spearblossom", "QUEST_WATCH_UPDATE", 65452));
table.insert(steps, CreateStep(77.49, 22.17, "The Waking Shores", "Ancient Hornswog", "Kill the frog", "QUEST_WATCH_UPDATE", 66076));
table.insert(steps, CreateStep(77.33, 29.88, "The Waking Shores", "Spelunker Lazee", "Rescue Spelunker", "QUEST_WATCH_UPDATE", 65452));
-- Wingrest Embrassy
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Naleidea Rivergleam", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Naleidea Rivergleam", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.29, 33.04, "The Waking Shores", "Scalecommander Cindrethresh", "Talk with Sendrax, then turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.96, 33.25, "The Waking Shores", "Boss Magor", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.31, 35.57, "The Waking Shores", "Ambassador Fastrasz", "Talk", "QUEST_WATCH_UPDATE", 69911));
table.insert(steps, CreateStep(76.31, 35.57, "The Waking Shores", nil, "Press the book", "QUEST_WATCH_UPDATE", 69911));
table.insert(steps, CreateStep(75.62, 34.16, "The Waking Shores", nil, "Press the Stone", "QUEST_WATCH_UPDATE", 69911));
table.insert(steps, CreateStep(78.39, 31.80, "The Waking Shores", nil, "Press the Brazier", "QUEST_WATCH_UPDATE", 69911));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Accept quest", "UNIT_QUEST_LOG_CHANGED"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Talk", nil, nil, "We were trained to only use these signal flares"));
table.insert(steps, CreateStep(76.36, 33.09, "The Waking Shores", "Warlord Breka Grimaxe", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.36, 33.09, "The Waking Shores", "Aster Cloudgaze", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.36, 33.09, "The Waking Shores", "Aster Cloudgaze", "Use the disk (1), jump off when it lands.", nil, nil, "Incredible! The elements"));
table.insert(steps, CreateStep(76.72, 34.55, "The Waking Shores", "Captain Garrick", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.27, 34.40, "The Waking Shores", "Sendrax", "Be near Sendrax", nil, nil, "Here they come!"));
table.insert(steps, CreateStep(76.36, 33.09, "The Waking Shores", "Aster Cloudgaze", "Use the disk (1), jump off when it lands.", nil, nil, "Incredible! The elements"));
table.insert(steps, CreateStep(76.36, 33.09, "The Waking Shores", "Aster Cloudgaze", "Complete and turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.19, 34.50, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.19, 34.50, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Majordomo Selistra", "Talk", nil, nil, "Cadet Sendrax, escort the"));
table.insert(steps, CreateStep(76.25, 34.40, "The Waking Shores", "Sendrax", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.25, 34.40, "The Waking Shores", "Sendrax", "Accept quest", "UNIT_QUEST_LOG_CHANGED"));
table.insert(steps, CreateStep(76.63, 33.56, "The Waking Shores", "Sendrax", "Talk", "QUEST_WATCH_UPDATE", 65760));
table.insert(steps, CreateStep(71.20, 40.76, "The Waking Shores", "Commander Lethanak", "Follow Sendrax", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(71.20, 40.76, "The Waking Shores", "Commander Lethanak", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(71.37, 44.59, "The Waking Shores", "Whimpering Whelpling", "Save Whelpling (Kill Djaradins)", "QUEST_WATCH_UPDATE", 65990));
table.insert(steps, CreateStep(71.00, 46.66, "The Waking Shores", "Whimpering Whelpling", "Save Whelpling (Kill Djaradins)", "QUEST_WATCH_UPDATE", 65990));
table.insert(steps, CreateStep(69.89, 45.28, "The Waking Shores", "Whimpering Whelpling", "Save Whelpling (Kill Djaradins)", "QUEST_WATCH_UPDATE", 65990));
table.insert(steps, CreateStep(69.37, 43.41, "The Waking Shores", "Whimpering Whelpling", "Save Whelpling (Kill Djaradins)", "QUEST_WATCH_UPDATE", 65990));
table.insert(steps, CreateStep(71.20, 40.76, "The Waking Shores", "Commander Lethanak", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(71.20, 40.76, "The Waking Shores", "Commander Lethanak", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(71.20, 40.76, "The Waking Shores", "Commander Lethanak", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(66.35, 34.92, "The Waking Shores", nil, "Run to Wrathion", "QUEST_WATCH_UPDATE", 65991));
table.insert(steps, CreateStep(66.35, 34.92, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(66.35, 34.92, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(66.35, 34.92, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(64.45, 33.16, "The Waking Shores", "Dragonhunter Igordan", "Kill", "QUEST_TURNED_IN", 66956));
table.insert(steps, CreateStep(62.95, 29.44, "The Waking Shores", "Meatgrinder Sotok", "Kill and get quest", "QUEST_ACCEPTED", 65995));
table.insert(steps, CreateStep(63.44, 28.87, "The Waking Shores", "Left", "Consult Left", "QUEST_WATCH_UPDATE", 65992));
table.insert(steps, CreateStep(65.10, 29.34, "The Waking Shores", "Right", "Consult Right", "QUEST_WATCH_UPDATE", 65992));
table.insert(steps, CreateStep(63.03, 33.34, "The Waking Shores", "Talonstalker Kavia", "Consult Talonstalker", "QUEST_WATCH_UPDATE", 65992));
table.insert(steps, CreateStep(62.68, 33.08, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.68, 33.08, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.68, 33.08, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.68, 33.08, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.04, 35.77, "The Waking Shores", "Injured Ruby Culler", "Injured Ruby Culler", "QUEST_WATCH_UPDATE", 65996));
table.insert(steps, CreateStep(61.11, 36.75, "The Waking Shores", "Injured Ruby Culler", "Injured Ruby Culler", "QUEST_WATCH_UPDATE", 65996));
table.insert(steps, CreateStep(59.05, 34.93, "The Waking Shores", "Injured Ruby Culler", "Injured Ruby Culler", "QUEST_WATCH_UPDATE", 65996));
table.insert(steps, CreateStep(59.05, 34.93, "The Waking Shores", "Caretaker Ventraz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.43, 31.02, "The Waking Shores", nil, "Kill elementals", "QUEST_WATCH_UPDATE", 66988));
table.insert(steps, CreateStep(59.05, 34.93, "The Waking Shores", "Caretaker Ventraz", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(56.64, 37.74, "The Waking Shores", "Injured Ruby Culler", "Injured Ruby Culler", "QUEST_WATCH_UPDATE", 65996));
table.insert(steps, CreateStep(55.00, 30.80, "The Waking Shores", "Caretaker Azkra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.00, 30.80, "The Waking Shores", "Caretaker Azkra", "Accept quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.15, 24.89, "The Waking Shores", "Sendrax", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(55.15, 24.89, "The Waking Shores", "Sendrax", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(55.15, 24.89, "The Waking Shores", nil, "Accept quest", "QUEST_ACCEPTED", 66000));
table.insert(steps, CreateStep(56.66, 24.79, "The Waking Shores", "Dragonhunter Igordan", "Kill", "QUEST_TURNED_IN", 70648));
table.insert(steps, CreateStep(56.16, 22.36, "The Waking Shores", "Sendrax", "Complete all quests and turn in", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(56.16, 22.36, "The Waking Shores", "Sendrax", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(56.16, 22.36, "The Waking Shores", "Sendrax", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(56.16, 22.36, "The Waking Shores", "Sendrax", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(56.16, 22.36, "The Waking Shores", "Sendrax", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(55.00, 30.69, "The Waking Shores", nil, "Grap and hand in egg", "QUEST_WATCH_UPDATE", 66001));
table.insert(steps, CreateStep(54.53, 30.84, "The Waking Shores", "Apprentice Caretaker Zefren", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(54.53, 30.84, "The Waking Shores", "Apprentice Caretaker Zefren", "Complete and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.06, 30.99, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(55.06, 30.99, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
-- Ruby Lifeshrine
table.insert(steps, CreateStep(62.26, 72.91, "The Waking Shores", "Alexstrasza the Life-Binder", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.26, 72.91, "The Waking Shores", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.26, 72.91, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.26, 72.91, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.70, 74.02, "The Waking Shores", "Xius", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.46, 72.47, "The Waking Shores", "Akxall", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(58.36, 67.19, "The Waking Shores", "Lord Andestrasz", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.69, 66.90, "The Waking Shores", "Lord Andestrasz", "Take Flight Path & Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.69, 66.90, "The Waking Shores", "Lord Andestrasz", "Complete dragonflying", "QUEST_ACCEPTED", 68796));
table.insert(steps, CreateStep(57.73, 66.76, "The Waking Shores", "Celormu", "Talk", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.11, 57.88, "The Waking Shores", "Glensera", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(74.11, 57.88, "The Waking Shores", nil, "Press the platform", "QUEST_WATCH_UPDATE", 68797));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.54, 56.94, "The Waking Shores", "Lithragosa", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(74.54, 56.94, "The Waking Shores", "Lithragosa", "Open Dragonriding skill Track", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(73.24, 52.20, "The Waking Shores", "Celormu", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.12, 55.04, "The Waking Shores", "Lord Andestrasz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.57, 68.72, "The Waking Shores", "Mother Elion", "Fly back and Talk to Mother Elion", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.77, 70.44, "The Waking Shores", "Zahkrana", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.77, 70.44, "The Waking Shores", "Zahkrana", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.21, 70.57, "The Waking Shores", "Amella", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.09, 71.46, "The Waking Shores", "Ruby Whelpling", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.34, 72.76, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.36, 72.95, "The Waking Shores", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.34, 72.99, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.49, 72.7, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.49, 72.7, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.43, 75.9, "The Waking Shores", "Commander Lethanak", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.43, 75.9, "The Waking Shores", "Commander Lethanak", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.79, 76.65, "The Waking Shores", "Enraged Cliff", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.76, 78.66, "The Waking Shores", "Enraged Cliff", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(61.04, 79.12, "The Waking Shores", "Enraged Cliff", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.91, 77.65, "The Waking Shores", "Enraged Cliff", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.39, 75.87, "The Waking Shores", "Commander Lethanak", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.39, 75.87, "The Waking Shores", "Commander Lethanak", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.47, 76.12, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.91, 75.95, "The Waking Shores", "Kildrumeh", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.34, 83.29, "The Waking Shores", nil, "Pick up egg", "QUEST_WATCH_UPDATE", 66121));
table.insert(steps, CreateStep(55.33, 83.29, "The Waking Shores", nil, "Pick up egg", "QUEST_WATCH_UPDATE", 66121));
table.insert(steps, CreateStep(54.8, 82.21, "The Waking Shores", "Klozicc the Ascended", "Kill", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(54.97, 80.97, "The Waking Shores", nil, "Pick up egg", "QUEST_TURNED_IN", 66121));
table.insert(steps, CreateStep(56.13, 81.27, "The Waking Shores", nil, "Pick up egg", "QUEST_WATCH_UPDATE", 66121));
table.insert(steps, CreateStep(53.73, 80.23, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(53.73, 80.23, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(53.73, 80.23, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(53.46, 83.03, "The Waking Shores", "Jadzigeth", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(53.73, 80.23, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(53.73, 80.23, "The Waking Shores", "Majordomo Selistra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(45.96, 81.48, "The Waking Shores", "Iyali", "Take Flightpath and Accept Meat-thod quest", "QUEST_ACCEPTED", 69898));
table.insert(steps, CreateStep(47.42, 77.25, "The Waking Shores", "Pudgy Riverbeast", "Find Meat", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.2, 78.43, "The Waking Shores", "Majordomo Selistra", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.19, 78.46, "The Waking Shores", "Majordomo Selistra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(46.12, 78.32, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.5, 66.84, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(42.5, 66.84, "The Waking Shores", "Scalecommander Emberthal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.53, 66.79, "The Waking Shores", "Scalecommander Emberthal", "Talk, then Make Inn home", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(42.53, 66.79, "The Waking Shores", "Scalecommander Emberthal", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(42.51, 66.79, "The Waking Shores", "Scalecommander Emberthal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.49, 66.83, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.44, 66.19, "The Waking Shores", "Fao the Relentless", "Talk and take map", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(42.8, 66.82, "The Waking Shores", "Forgemaster Bazentus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(43.75, 67.23, "The Waking Shores", "Archivist Edress", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(42.26, 69.33, "The Waking Shores", "Talonstalker Kavia", "Talk and complete", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(42.48, 66.85, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(42.48, 66.85, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(42.51, 66.83, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.51, 66.83, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(35.66, 68.55, "The Waking Shores", "Piercer Gigra", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(34.82, 66.97, "The Waking Shores", "Olphis the Molten", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(35.59, 60.72, "The Waking Shores", "Modak Flamespit", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(34.03, 61.32, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(34.03, 61.32, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(34.03, 61.32, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(34.03, 61.32, "The Waking Shores", "Wrathion", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(29.07, 58.79, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(29.07, 58.79, "The Waking Shores", "Wrathion", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(27.14, 57.07, "The Waking Shores", "Champion Choruk", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(26.42, 58.74, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(26.42, 58.74, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(26.4, 58.75, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(27.32, 62.57, "The Waking Shores", "Wrathion", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(27.31, 62.62, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(27.28, 62.78, "The Waking Shores", "Forgemaster Bazentus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(23.84, 59.16, "The Waking Shores", "Scalecommander Emberthal", "Complete quest", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(27.28, 62.78, "The Waking Shores", "Forgemaster Bazentus", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(27.28, 62.78, "The Waking Shores", "Forgemaster Bazentus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.65, 60.94, "The Waking Shores", "Forgemaster Bazentus", "Click forge", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.74, 61.21, "The Waking Shores", "Forgemaster Bazentus", "Complete and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.71, 61.14, "The Waking Shores", "Forgemaster Bazentus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.64, 60.94, "The Waking Shores", "Forgemaster Bazentus", "Click forge", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.64, 60.94, "The Waking Shores", "Forgemaster Bazentus", "Click forge", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.7, 61.1, "The Waking Shores", "Forgemaster Bazentus", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.71, 61.14, "The Waking Shores", "Forgemaster Bazentus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(27.34, 62.58, "The Waking Shores", "Wrathion", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(27.34, 62.58, "The Waking Shores", "Wrathion", "Travel", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.48, 55.57, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.48, 55.57, "The Waking Shores", "Wrathion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.31, 55.88, "The Waking Shores", "Sabellian", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.99, 55.19, "The Waking Shores", "Left", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(26.37, 54.64, "The Waking Shores", "Talonstalker Kavia", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.14, 56.32, "The Waking Shores", "Archivist Edress", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.14, 56.32, "The Waking Shores", "Archivist Edress", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.4, 57.82, "The Waking Shores", "Forgemaster Bazentus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.33, 58.8, "The Waking Shores", "Baskilan", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.43, 55.58, "The Waking Shores", "Wrathion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.33, 55.92, "The Waking Shores", "Sabellian", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.34, 55.87, "The Waking Shores", "Sabellian", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(43.83, 66.4, "The Waking Shores", "Sabellian", "Use Hearthstone and Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.92, 67.3, "The Waking Shores", "Sabellian", "Escort and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.94, 67.31, "The Waking Shores", "Sabellian", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.56, 68.69, "The Waking Shores", "Mother Elion", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.56, 68.69, "The Waking Shores", "Mother Elion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.57, 68.71, "The Waking Shores", "Mother Elion", "Complete and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.56, 68.69, "The Waking Shores", "Mother Elion", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.35, 73.03, "The Waking Shores", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.35, 73.03, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.55, 68.59, "The Waking Shores", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.55, 68.59, "The Waking Shores", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(45.95, 81.47, "The Waking Shores", "Iyali", "Fly and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(48.29, 88.59, "The Waking Shores", "Ambassador Taurasza", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(48.29, 88.59, "The Waking Shores", "Ambassador Taurasza", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(77.73, 23.9, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(77.73, 23.9, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(78.52, 26.98, "Ohn'ahran Plains", "Blazing Proto-Dragon", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(78.62, 25.43, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(78.62, 25.43, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(85.29, 25.39, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(85.32, 25.37, "Ohn'ahran Plains", "Loyal Bakar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(84.57, 25.25, "Ohn'ahran Plains", "Muqur Rain-Touched", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(84.41, 24.98, "Ohn'ahran Plains", "Farrier Roscha", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(84.38, 24.97, "Ohn'ahran Plains", "Apprentice Ehri", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(85.7, 25.32, "Ohn'ahran Plains", "Sansok Khan", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(85.7, 25.32, "Ohn'ahran Plains", "Sansok Khan", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(85.7, 25.32, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(85.7, 25.32, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(85.79, 26.56, "Ohn'ahran Plains", "Aru", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(83.94, 25.93, "Ohn'ahran Plains", "Beastmaster Nuqut", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(85.58, 20.9, "Ohn'ahran Plains", "Ohn Seshteng", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(84.68, 22.87, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(84.68, 22.87, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(84.68, 22.87, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(83.19, 23.72, "Ohn'ahran Plains", "Scout Tomul", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(85.01, 15.22, "Ohn'ahran Plains", "Ravenous Rockfang", "Get Gizzard and Fermur", "QUEST_WATCH_UPDATE", 70319));
table.insert(steps, CreateStep(85.01, 15.22, "Ohn'ahran Plains", "Ravenous Rockfang", "Get Gizzard and Fermur", "QUEST_WATCH_UPDATE", 70319));
table.insert(steps, CreateStep(77.73, 18.55, "Ohn'ahran Plains", "Swift Hornstrider", "Get Scale", "QUEST_WATCH_UPDATE", 70319));
table.insert(steps, CreateStep(75.13, 25.04, "Ohn'ahran Plains", "Clearwater Ottuk", "Get Heart", "QUEST_WATCH_UPDATE", 70319));
table.insert(steps, CreateStep(75.65, 31.63, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.65, 31.63, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.7, 31.9, "Ohn'ahran Plains", nil, "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(77.95, 35.3, "Ohn'ahran Plains", "Konkhular", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(78.75, 30.91, "Ohn'ahran Plains", "Plainswalker Bull", "Kill Elephants", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(81.22, 29.87, "Ohn'ahran Plains", "Mudfin Mudrunner", "Talk", "QUEST_WATCH_UPDATE", 65950));
table.insert(steps, CreateStep(80.57, 30.77, "Ohn'ahran Plains", "Khasar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(80.57, 30.77, "Ohn'ahran Plains", "Khasar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(80.58, 30.77, "Ohn'ahran Plains", "Khasar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(80.58, 30.77, "Ohn'ahran Plains", "Khasar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(80.58, 30.77, "Ohn'ahran Plains", "Khasar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(84.43, 25.01, "Ohn'ahran Plains", "Farrier Roscha", "Complete all Murloc quests, then Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(84.43, 25.01, "Ohn'ahran Plains", "Farrier Roscha", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(84.57, 25.27, "Ohn'ahran Plains", "Muqur Rain-Touched", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.65, 31.69, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.65, 31.69, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(75.65, 31.69, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(69.99, 37.96, "Ohn'ahran Plains", "Ohn Seshteng", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(69.99, 37.96, "Ohn'ahran Plains", "Ohn Seshteng", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(69.95, 37.96, "Ohn'ahran Plains", "Ohn Seshteng", "Complete and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(69.99, 37.96, "Ohn'ahran Plains", "Ohn Seshteng", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(69.95, 37.96, "Ohn'ahran Plains", "Ohn Seshteng", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(70, 37.97, "Ohn'ahran Plains", "Ohn Seshteng", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(70.04, 37.99, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.45, 39.58, "Ohn'ahran Plains", "Sansok Khan", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.45, 39.58, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.45, 39.58, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.45, 39.58, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.45, 39.58, "Ohn'ahran Plains", "Sansok Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.6, 40.5, "Ohn'ahran Plains", "Hunter Narman", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.79, 40.66, "Ohn'ahran Plains", "Make Inn Home", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.43, 40.73, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.35, 40.76, "Ohn'ahran Plains", "Guard Bahir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.96, 41.44, "Ohn'ahran Plains", "Nokhud Fighter", "Defeat", "QUEST_WATCH_UPDATE", 66017));
table.insert(steps, CreateStep(59.18, 37.66, "Ohn'ahran Plains", "Qariin Dotur", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.18, 37.66, "Ohn'ahran Plains", "Qariin Dotur", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.17, 37.59, "Ohn'ahran Plains", "Qariin Dotur", "Complete and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.01, 37.37, "Ohn'ahran Plains", "Elder Odgerel", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.37, 37.61, "Ohn'ahran Plains", "Agari Dotur", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.37, 37.71, "Ohn'ahran Plains", "Quartermaster Huseng", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.17, 36.41, "Ohn'ahran Plains", "Windsage Kven", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.19, 35.76, "Ohn'ahran Plains", "Hearthkeeper Erden", "Buy Honey", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.79, 35.48, "Ohn'ahran Plains", "Windsage Dawa", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.97, 33.67, "Ohn'ahran Plains", "Ohn Seshteng", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.97, 33.67, "Ohn'ahran Plains", "Ohn Seshteng", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.12, 34.08, "Ohn'ahran Plains", "Windsage Ordven", "Accept quest", "QUEST_ACCEPTED")); -- A disgrunded initiate?
table.insert(steps, CreateStep(63.81, 35.91, "Ohn'ahran Plains", "Ohn Arasara", "Pick flowers and Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.97, 33.73, "Ohn'ahran Plains", "Ohn Seshteng", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.18, 35.71, "Ohn'ahran Plains", "Hearthkeeper Erden", "Buy milk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(65.97, 25.11, "Ohn'ahran Plains", "Telemancer Aerilyn", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(65.9, 25.13, "Ohn'ahran Plains", "Telemancer Aerilyn", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(64.03, 18.32, "Ohn'ahran Plains", "Skyscribe Adenedal", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(64.03, 18.32, "Ohn'ahran Plains", "Skyscribe Adenedal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(64.03, 18.32, "Ohn'ahran Plains", "Skyscribe Adenedal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.94, 15.82, "Ohn'ahran Plains", "Sundered Enforcer", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(64.34, 15.68, "Ohn'ahran Plains", "Tarasek Laborer", "Pick up", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(64.02, 18.27, "Ohn'ahran Plains", "Skyscribe Adenedal", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.92, 18.59, "Ohn'ahran Plains", "Tserasor the Preserver", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.42, 18.48, "Ohn'ahran Plains", "Sootscale the Indomitable", "KILL", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(61.74, 18.63, "Ohn'ahran Plains", nil, "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.58, 16.46, "Ohn'ahran Plains", "Malifron", "KILL", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.13, 16.35, "Ohn'ahran Plains", "Skyscribe Adenedal", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.13, 16.35, "Ohn'ahran Plains", "Skyscribe Adenedal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.62, 17.37, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.62, 17.37, "Ohn'ahran Plains", "Hypoxicron", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(66.31, 24.34, "Ohn'ahran Plains", "Skyscribe Adenedal", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(66.31, 24.34, "Ohn'ahran Plains", "Skyscribe Adenedal", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(65.99, 25.07, "Ohn'ahran Plains", "Telemancer Aerilyn", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.54, 41.05, "Ohn'ahran Plains", "Provisioner Zara", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.42, 41.69, "Ohn'ahran Plains", "Scout Tomul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.39, 41.66, "Ohn'ahran Plains", "Aru", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.41, 39.53, "Ohn'ahran Plains", "Sansok Khan", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(61.43, 39.55, "Ohn'ahran Plains", "Sansok Khan", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.06, 40.44, "Ohn'ahran Plains", "Gemisath", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.06, 40.44, "Ohn'ahran Plains", "Gemisath", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.06, 40.44, "Ohn'ahran Plains", "Gemisath", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.3, 37.91, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.33, 38.02, "Ohn'ahran Plains", "Khansguard Akato", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.5, 38.73, "Ohn'ahran Plains", "Scout Tomul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.76, 39.41, "Ohn'ahran Plains", "Nokhud Reaver", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(58.2, 39.36, "Ohn'ahran Plains", "Guard Bahir", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.08, 42.65, "Ohn'ahran Plains", "Old Arbhog", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(55.36, 38.4, "Ohn'ahran Plains", "Matchmaker Osila", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(56.09, 38.24, "Ohn'ahran Plains", "Matchmaker Osila", "Talk", "QUEST_WATCH_UPDATE", 70739));
table.insert(steps, CreateStep(60.32, 38.07, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.32, 38.07, "Ohn'ahran Plains", "Khansguard Akato", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.32, 38.07, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(62.84, 35.43, "Ohn'ahran Plains", "Windsage Dawa", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(62.84, 35.43, "Ohn'ahran Plains", "Windsage Dawa", "Accept quest", "QUEST_TURNED_IN")); -- After My Ohn Heart available ?
table.insert(steps, CreateStep(60.05, 37.52, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.05, 37.52, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.6, 40.56, "Ohn'ahran Plains", "Hunter Narman", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.59, 40.45, "Ohn'ahran Plains", "Hunter Narman", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(62.03, 41.8, "Ohn'ahran Plains", "Beastmaster Tirren", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.02, 48.56, "Ohn'ahran Plains", "Sunscale Behemoth", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.67, 60.34, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.71, 60.52, "Ohn'ahran Plains", "Hunter Narman", "Turn in quest", "QUEST_TURNED_IN"));
-- Teerakai
table.insert(steps, CreateStep(41.89, 61.79, "Ohn'ahran Plains", "Khansguard Jebotai", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(41.87, 61.8, "Ohn'ahran Plains", "Khansguard Jebotai", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(40.97, 61.59, "Ohn'ahran Plains", "Elder Yuvari", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(39.05, 65.99, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.05, 65.99, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(37.16, 65.68, "Ohn'ahran Plains", "Tombcaller Ganzaya", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(37.06, 65.51, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(39.05, 65.99, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.05, 65.99, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(36.2, 64.19, "Ohn'ahran Plains", "Risen Bakar", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(33.78, 65.37, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(33.78, 65.37, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(33.78, 65.37, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(35.61, 68.14, "Ohn'ahran Plains", "Overseer Zambul", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(33.78, 65.36, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(33.78, 65.36, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(32.82, 71.73, "Ohn'ahran Plains", nil, "Kill", "QUEST_WATCH_UPDATE", 66656));
table.insert(steps, CreateStep(30.86, 71.14, "Ohn'ahran Plains", nil, "Kill", "QUEST_WATCH_UPDATE", 66656));
table.insert(steps, CreateStep(30.86, 71.14, "Ohn'ahran Plains", nil, "Kill", "QUEST_WATCH_UPDATE", 66656));
table.insert(steps, CreateStep(30.86, 71.14, "Ohn'ahran Plains", nil, "Kill", "QUEST_WATCH_UPDATE", 66656));
table.insert(steps, CreateStep(30.89, 71.19, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(30.89, 71.19, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(31.47, 70.85, "Ohn'ahran Plains", "Tombcaller Arban", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(31.09, 71, "Ohn'ahran Plains", "Tombcaller Arban", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(31.48, 71.49, "Ohn'ahran Plains", "Tombcaller Arban", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(31.45, 71.43, "Ohn'ahran Plains", "Initiate Zorig", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(31.45, 71.43, "Ohn'ahran Plains", "Initiate Zorig", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(37.54, 59.49, "Ohn'ahran Plains", "Scout Khenyug", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(39.57, 56.43, "Ohn'ahran Plains", "Herbalist Agura", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(39.55, 55.4, "Ohn'ahran Plains", "Khansguard Hojin", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(40.77, 56.33, "Ohn'ahran Plains", "Quartermaster Gensai", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(41.62, 56.75, "Ohn'ahran Plains", "Elder Nazuun", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(41.62, 56.75, "Ohn'ahran Plains", "Elder Nazuun", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(42.24, 47.34, "Ohn'ahran Plains", "Mara'nar the Thunderous", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(44.2, 48.39, "Ohn'ahran Plains", "Spider Eggs", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(44.94, 49.05, "Ohn'ahran Plains", "Skaara", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.65, 51.45, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(50.15, 50.95, "Ohn'ahran Plains", "Thunderspine Crasher", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(49.34, 49.51, "Ohn'ahran Plains", nil, "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(49.34, 49.43, "Ohn'ahran Plains", "Himia, The Blessed", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(41.6, 56.75, "Ohn'ahran Plains", "Elder Nazuun", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(41.6, 56.75, "Ohn'ahran Plains", "Elder Nazuun", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(41.6, 56.75, "Ohn'ahran Plains", "Elder Nazuun", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(40.14, 57.81, "Ohn'ahran Plains", "Elder Nazuun", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(41.6, 56.74, "Ohn'ahran Plains", "Elder Nazuun", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(41.86, 61.76, "Ohn'ahran Plains", "Khansguard Jebotai", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(41.86, 61.76, "Ohn'ahran Plains", "Khansguard Jebotai", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(36.84, 57.29, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(36.82, 57.31, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(36.82, 57.31, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(44.55, 61.95, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.51, 63.22, "Ohn'ahran Plains", "Unidentified Centaur", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(49.31, 63.21, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(49.31, 63.18, "Ohn'ahran Plains", "Tigari Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(49.31, 63.18, "Ohn'ahran Plains", "Tigari Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(48.92, 69, "Ohn'ahran Plains", "Shela the Windbinder", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(49.55, 67.13, "Ohn'ahran Plains", "Nokhud Mystic-Hunter", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(49.81, 67.02, "Ohn'ahran Plains", "Eaglemaster Niraak", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(49.36, 63.18, "Ohn'ahran Plains", "Tigari Khan", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(49.36, 63.18, "Ohn'ahran Plains", "Tigari Khan", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(49.39, 63.2, "Ohn'ahran Plains", "Tigari Khan", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.11, 68.97, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(58.11, 68.97, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.11, 68.97, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.11, 68.97, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.89, 66.82, "Ohn'ahran Plains", "Prozela Galeshot", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.65, 63.55, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.65, 63.55, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.65, 63.55, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.65, 63.55, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.41, 62.81, "Ohn'ahran Plains", "Initiate Boku", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.41, 62.81, "Ohn'ahran Plains", "Initiate Boku", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.05, 37.55, "Ohn'ahran Plains", "Khanam Matra Sarest", "HS and Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.05, 37.55, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.05, 37.55, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.05, 37.55, "Ohn'ahran Plains", "Khanam Matra Sarest", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(73.01, 40.57, "Ohn'ahran Plains", "Khanam Matra Sarest", "Skip the lion and fly here. Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(73.01, 40.57, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.02, 40.91, "Ohn'ahran Plains", "Warmonger Kharad", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(76.69, 40.91, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.69, 40.91, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(76.69, 40.91, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.69, 40.91, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.4, 50.37, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(72.42, 50.71, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.31, 50.69, "Ohn'ahran Plains", "Gerithus", "Talk", "QUEST_WATCH_UPDATE"));
-- Shady Sanctuary

table.insert(steps, CreateStep(28.27, 57.71, "Ohn'ahran Plains", "Merithra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(28.27, 57.71, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(29.97, 58.33, "Ohn'ahran Plains", "Gracus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(30.19, 55.73, "Ohn'ahran Plains", "Sidra the Mender", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(29.13, 55.29, "Ohn'ahran Plains", "Guard-Captain Alowen", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(29.29, 56.44, "Ohn'ahran Plains", "Aronus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(29.71, 60.02, "Ohn'ahran Plains", "Viranikus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(29.61, 58.68, "Ohn'ahran Plains", "Gracus", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(29.54, 58.76, "Ohn'ahran Plains", "Gracus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(28.29, 57.7, "Ohn'ahran Plains", "Merithra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(28.28, 57.69, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(30.36, 58.2, "Ohn'ahran Plains", "Gracus", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(30.36, 58.19, "Ohn'ahran Plains", "Gracus", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(27.15, 56.61, "Ohn'ahran Plains", "Queasy Hornswog", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.11, 56.91, "Ohn'ahran Plains", "Celina Crunchyleaves", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.85, 64.46, "Ohn'ahran Plains", "Theramus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.47, 63.02, "Ohn'ahran Plains", "Celina Crunchyleaves", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.46, 62.99, "Ohn'ahran Plains", "Celina Crunchyleaves", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.48, 63, "Ohn'ahran Plains", "Felina Starrunner", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(22.89, 66.34, "Ohn'ahran Plains", "Territorial Coastling", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(22.67, 62.59, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.44, 63, "Ohn'ahran Plains", "Celina Crunchyleaves", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.46, 62.98, "Ohn'ahran Plains", "Felina Starrunner", "Talk", "QUEST_WATCH_UPDATE"));

table.insert(steps, CreateStep(24.52, 63.07, "Ohn'ahran Plains", "Felina Starrunner", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.52, 63.07, "Ohn'ahran Plains", "Felina Starrunner", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.85, 64.44, "Ohn'ahran Plains", "Theramus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.48, 63.04, "Ohn'ahran Plains", "Felina Starrunner", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.48, 63.04, "Ohn'ahran Plains", "Felina Starrunner", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.47, 63.01, "Ohn'ahran Plains", "Celina Crunchyleaves", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.89, 60.34, "Ohn'ahran Plains", "Injured Cub", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.47, 63.01, "Ohn'ahran Plains", "Celina Crunchyleaves", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.47, 63.01, "Ohn'ahran Plains", "Felina Starrunner", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.47, 63.01, "Ohn'ahran Plains", "Celina Crunchyleaves", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.59, 64.15, "Ohn'ahran Plains", "Theramus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.6, 63.97, "Ohn'ahran Plains", "Celina Crunchyleaves", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.57, 63.98, "Ohn'ahran Plains", "Felina Starrunner", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.96, 65.87, "Ohn'ahran Plains", "Theramus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(26.29, 65.37, "Ohn'ahran Plains", "Ripsaw the Stalker", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.97, 65.84, "Ohn'ahran Plains", "Theramus", "Turn in quest", "QUEST_TURNED_IN"));

table.insert(steps, CreateStep(29.06, 58.68, "Ohn'ahran Plains", "Gracus", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(27.58, 46.09, "Ohn'ahran Plains", "Belika", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.74, 44.29, "Ohn'ahran Plains", "Boku", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(26.18, 40.13, "Ohn'ahran Plains", "Ohn Seshteng", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.66, 40.5, "Ohn'ahran Plains", "Merithra", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.68, 40.47, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(25.65, 40.52, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));

table.insert(steps, CreateStep(24.14, 36.75, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.15, 36.78, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(24.17, 36.8, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));

table.insert(steps, CreateStep(23.86, 39.46, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(23.08, 37.46, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(21.65, 37.5, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.86, 35.08, "Ohn'ahran Plains", "Primalist Storm-Summoner", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(24.84, 35.05, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.84, 35.05, "Ohn'ahran Plains", "Khanam Matra Sarest", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(24.84, 35.05, "Ohn'ahran Plains", "Khanam Matra Sarest", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(25.79, 34.41, "Ohn'ahran Plains", "Ty'foon the Ascended", "Kill", "QUEST_WATCH_UPDATE")); -- EXP ?
table.insert(steps, CreateStep(22.49, 39.67, "Ohn'ahran Plains", "Stormbound Proto-Drake", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(22.88, 40.19, "Ohn'ahran Plains", "Gerithus", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(25.68, 48.39, "Ohn'ahran Plains", "Merithra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(25.68, 48.39, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(22.15, 50.97, "Ohn'ahran Plains", "Merithra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(22.15, 50.97, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(22.28, 50.9, "Ohn'ahran Plains", "Sansok Khan", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(22.15, 50.97, "Ohn'ahran Plains", "Merithra", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(22.15, 50.97, "Ohn'ahran Plains", "Merithra", "Accept quest", "QUEST_ACCEPTED"));

table.insert(steps, CreateStep(71.61, 80.55, "Ohn'ahran Plains", "Masud the Wise", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(71.61, 80.55, "Ohn'ahran Plains", "Masud the Wise", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.01, 81.09, "Ohn'ahran Plains", "Azley", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.01, 81.07, "Ohn'ahran Plains", "Azley", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.48, 82.22, "Ohn'ahran Plains", "Forkriver Goat", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(74.57, 81.04, "Ohn'ahran Plains", "Bree'jo", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(77.26, 73.17, "Ohn'ahran Plains", "Duncan Ironeye", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(67.07, 80.93, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));

table.insert(steps, CreateStep(71.61, 80.55, "Ohn'ahran Plains", "Masud the Wise", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(71.61, 80.55, "Ohn'ahran Plains", "Masud the Wise", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.01, 81.09, "Ohn'ahran Plains", "Azley", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.01, 81.07, "Ohn'ahran Plains", "Azley", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.57, 81.04, "Ohn'ahran Plains", "Bree'jo", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(77.26, 73.17, "Ohn'ahran Plains", "Duncan Ironeye", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(67.07, 80.93, "Ohn'ahran Plains", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(74.48, 82.22, "Ohn'ahran Plains", "Forkriver Goat", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(72.04, 81.1, "Ohn'ahran Plains", "Azley", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(72.04, 81.1, "Ohn'ahran Plains", "Azley", "Turn in quest", "QUEST_TURNED_IN"));

-- Necessary? FROM HERE:
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(19.03, 24.01, "The Azure Span", "Zon'Wogi", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(19, 23.32, "The Azure Span", "Modurun Sixtoes", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(21.42, 25.74, "The Azure Span", "Thickmane Matriach", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.28, 25.61, "The Azure Span", "Striped Bruffalon", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(16.19, 27.51, "The Azure Span", "Vorquin Strider", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.36, 26.3, "The Azure Span", "Sky Vixen Shokhari", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.77, 24.47, "The Azure Span", "Willa Stronghinge", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(19.03, 23.99, "The Azure Span", "Zon'Wogi", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.98, 23.37, "The Azure Span", "Modurun Sixtoes", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.56, 23.71, "The Azure Span", "Manny Read", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(17.28, 23.26, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(19.16, 24.68, "The Azure Span", "Gannar Fullpack", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(19.4, 23.95, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(20.02, 24.2, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(17.61, 28.24, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.55, 23.73, "The Azure Span", "Manny Read", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.63, 23.7, "The Azure Span", "Thanessa Silverbloom", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.77, 24.45, "The Azure Span", "Guo-Hee Calmwater", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(17.31, 26.13, "The Azure Span", "Mysterious Apparition", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.75, 24.43, "The Azure Span", "Guo-Hee Calmwater", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(18.78, 24.42, "The Azure Span", "Mysterious Apparition", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(18.77, 24.46, "The Azure Span", "Mysterious Apparition", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.79, 24.42, "The Azure Span", "Mysterious Apparition", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(20.55, 35.69, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(18.43, 34.79, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.9, 36.98, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(17.58, 36.96, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.79, 24.42, "The Azure Span", "Mysterious Apparition", "Turn in quest", "QUEST_TURNED_IN"));
-- TO HERE.

table.insert(steps, CreateStep(20.55, 35.69, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(18.43, 34.79, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(18.9, 36.98, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(17.58, 36.96, "The Azure Span", "Brackenhide Scrapper", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(16.77, 37.31, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(16.77, 37.31, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(16.77, 37.26, "The Azure Span", "Norukk", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(16.77, 37.22, "The Azure Span", "Brena", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(17.54, 37.94, "The Azure Span", "Nomurok", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(17.42, 38.67, "The Azure Span", "Tuyuki", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(16.78, 37.29, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(16.78, 37.26, "The Azure Span", "Norukk", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(16.77, 37.23, "The Azure Span", "Brena", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(16.77, 37.31, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(16.77, 37.31, "The Azure Span", "Kalecgos", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(15.28, 39.43, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(15.28, 39.43, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(15.34, 39.49, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(15.1, 39.53, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(15.27, 39.18, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(15.49, 39.3, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(17, 41.35, "The Azure Span", "Vakril", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(16.15, 41.41, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
-- Iskaara
table.insert(steps, CreateStep(16.13, 41.43, "The Azure Span", "Brena", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(13.25, 49.51, "The Azure Span", "Brena", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.25, 49.51, "The Azure Span", "Brena", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(13.25, 49.51, "The Azure Span", "Brena", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(13.14, 49.22, "The Azure Span", "Murik", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(12.93, 48.73, "The Azure Span", "Hanu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(12.95, 48.67, "The Azure Span", "Norukk", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.19, 48.56, "The Azure Span", "Arvik", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.91, 50.05, "The Azure Span", "Rokkutuk", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.21, 48.88, "The Azure Span", "Tatto", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.19, 48.79, "The Azure Span", "Bukarakikk", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(12.44, 49.41, "The Azure Span", "Elder Nappa", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(12.44, 49.36, "The Azure Span", "Elder Poa", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(12.43, 49.4, "The Azure Span", "Elder Nappa", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.16, 49.22, "The Azure Span", "Murik", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.15, 48.61, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.73, 47.65, "The Azure Span", "Auntie Kaunnie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(16.11, 50.46, "The Azure Span", "Rowie", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(16.12, 50.45, "The Azure Span", "Rowie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(16.12, 50.45, "The Azure Span", "Rowie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(16.73, 49.33, "The Azure Span", "Toejam the Terrible", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.78, 49.02, "The Azure Span", "Auntie Kaunnie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.24, 49.56, "The Azure Span", "Brena", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.24, 49.54, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(13.23, 49.52, "The Azure Span", "Brena", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(13.13, 50.14, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(12.95, 50.4, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(12.95, 50.4, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(10.62, 46.89, "The Azure Span", "Neelo", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.63, 44.39, "The Azure Span", "Mordigan Ironjaw", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.22, 45.11, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.61, 44.38, "The Azure Span", "Mordigan Ironjaw", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.63, 44.33, "The Azure Span", "LOU-C Fitzcog", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.65, 44.28, "The Azure Span", "Examiner Rowe", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.63, 44.25, "The Azure Span", "Aelnara", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(10.36, 43.36, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "Examiner Rowe", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "Aelnara", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "LOU-C Fitzcog", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "LOU-C Fitzcog", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.63, 44.3, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.61, 46.91, "The Azure Span", "Neelo", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(10.61, 46.91, "The Azure Span", "Neelo", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.63, 44.39, "The Azure Span", "Mordigan Ironjaw", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.22, 45.11, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.61, 44.38, "The Azure Span", "Mordigan Ironjaw", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.63, 44.33, "The Azure Span", "LOU-C Fitzcog", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.65, 44.28, "The Azure Span", "Examiner Rowe", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.63, 44.25, "The Azure Span", "Aelnara", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(10.36, 43.36, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "Examiner Rowe", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "Aelnara", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "LOU-C Fitzcog", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.65, 44.29, "The Azure Span", "LOU-C Fitzcog", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.63, 44.3, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(7.63, 44.3, "The Azure Span", "LOU-C Fitzcog", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.63, 44.3, "The Azure Span", "LOU-C Fitzcog", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.5, 44.31, "The Azure Span", "Wayun", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(9.38, 42.56, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.01, 41.33, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(9.96, 39.69, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.64, 41.24, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.76, 41.19, "The Azure Span", "Aelnara", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(10.76, 41.19, "The Azure Span", "Aelnara", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(11.23, 41.04, "The Azure Span", "Mordigan Ironjaw", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.77, 41.2, "The Azure Span", "Aelnara", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(10.77, 41.2, "The Azure Span", "Aelnara", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(7.66, 44.29, "The Azure Span", "Examiner Rowe", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(7.47, 44.3, "The Azure Span", "Wayun", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(13.84, 49.47, "The Azure Span", "Jinkutuk", "Buy 7 Frigidfish", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(10.61, 46.9, "The Azure Span", "Neelo", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(11.33, 53.74, "The Azure Span", "Krojek The Shoreprowler", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(12.52, 49.85, "The Azure Span", "Bukarakikk", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(46.62, 38.83, "The Azure Span", "Hemet Nesingwary", "Hearthstone and Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(49.01, 36.39, "The Azure Span", "Frostfist", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Fly to Azure Archives and Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.46, 63.02, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(65.82, 25.34, "The Azure Span", "Drok Scrollstabber", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(66.08, 25.45, "The Azure Span", "Proto-Drake", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(65.83, 25.34, "The Azure Span", "Drok Scrollstabber", "Turn in quest", "QUEST_TURNED_IN"));

-- Necessary?
table.insert(steps, CreateStep(65.87, 26.37, "The Azure Span", "Hemet Nesingwary", "Accept quest", "QUEST_ACCEPTED")); -- ?
table.insert(steps, CreateStep(63.15, 58.36, "The Azure Span", "Hemet Nesingwary Jr.", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.15, 58.36, "The Azure Span", "Hemet Nesingwary Jr.", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.19, 58.38, "The Azure Span", "Maddy Scattershot", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.24, 58.6, "The Azure Span", "Garz", "Accept quest", "QUEST_ACCEPTED"));
-- To here

table.insert(steps, CreateStep(65.61, 54.85, "The Azure Span", "Narn", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.52, 53.02, "The Azure Span", "Garz", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(63.5, 53.02, "The Azure Span", "Garz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.5, 53.02, "The Azure Span", "Garz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(63.5, 53.02, "The Azure Span", "Garz", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.99, 51.41, "The Azure Span", "Radza Thunderclaw", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.98, 51.38, "The Azure Span", "Khargall Fivefangs", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.95, 50.55, "The Azure Span", "Narn", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.95, 50.55, "The Azure Span", "Narn", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.94, 50.49, "The Azure Span", "Radza Thunderclaw", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.94, 50.49, "The Azure Span", "Radza Thunderclaw", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.57, 49.56, "The Azure Span", "Stoneheart", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.93, 50.48, "The Azure Span", "Radza Thunderclaw", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(70.11, 33.33, "The Azure Span", "Summoned Destroyer", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(70.04, 35.24, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(70.04, 35.24, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(70.03, 35.3, "The Azure Span", "Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(70.03, 35.3, "The Azure Span", "Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(72.9, 38.61, "The Azure Span", "Ruvin Stonegrinder", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(73.79, 38.29, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(74.45, 37.83, "The Azure Span", "Archmage Khadgar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(74.45, 37.83, "The Azure Span", "Archmage Khadgar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(74.45, 37.83, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(74.45, 37.83, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.45, 37.83, "The Azure Span", "Archmage Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(74.57, 38.6, "The Azure Span", "Primal Lava Elemental", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(75.28, 37.26, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(75.61, 38.32, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(76.11, 37.92, "The Azure Span", "Primalist Worshipper", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(76.55, 38.92, "The Azure Span", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(76.95, 39.43, "The Azure Span", "Archmage Khadgar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.95, 39.43, "The Azure Span", "Archmage Khadgar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(76.95, 39.43, "The Azure Span", "Archmage Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(78.4, 39.98, "The Azure Span", "Kalecgos", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(78.4, 39.98, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(79.32, 36.45, "The Azure Span", "Korthrox the Destroyer", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(78, 32.45, "The Azure Span", "Archmage Khadgar", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(78, 32.45, "The Azure Span", "Archmage Khadgar", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(39.5, 63.01, "The Azure Span", "Sindragosa", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(39.5, 63.01, "The Azure Span", "Sindragosa", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(39.5, 63.01, "The Azure Span", "Kalecgos", "Accept quest", "QUEST_ACCEPTED"));

-- Valdrakken
table.insert(steps, CreateStep(58.24, 35.44, "Valdrakken", "Unatos", "Make Inn your home & Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.89, 36.26, "Valdrakken", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.96, 35.86, "Valdrakken", "Alexstrasza the Life-Binder", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.06, 36.03, "Valdrakken", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.81, 33.23, "Valdrakken", "Captain Drine", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.79, 33.31, "Valdrakken", "Captain Drine", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(54.58, 41.03, "Valdrakken", "Watcher Koranos", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(36.74, 50.55, "Valdrakken", "Provisioner Thom", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(54.68, 47.38, "Valdrakken", "Captain Drine", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(34.72, 61.18, "Valdrakken", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(36.46, 62.75, "Valdrakken", "Dothenos", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(46.73, 79.02, "Valdrakken", "Kaestrasz", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.04, 54.99, "Valdrakken", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(47.02, 47.93, "The Roasted Ram", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(38.14, 44.98, "Valdrakken", "Valdrakken Citizen", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(54.53, 47.46, "Valdrakken", "Captain Drine", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(54.53, 47.46, "Valdrakken", "Captain Drine", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(35.85, 82.54, "Thaldraszus", "Guardian Velomir", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(35.85, 82.54, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(35.87, 82.54, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(35.87, 82.54, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(36.25, 83.73, "Thaldraszus", "Mangled Corpse", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(36.46, 85.41, "Thaldraszus", "Mangled Corpse", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(35.77, 84.22, "Thaldraszus", "Badly Injured Guardian", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(36.83, 85.57, "Thaldraszus", "Lookout Mordren", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(37.6, 83.12, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(37.6, 83.12, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(37.6, 83.12, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(37.88, 83.26, "Thaldraszus", nil, "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(38.55, 83.4, "Thaldraszus", nil, "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(37.63, 83.13, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(37.63, 83.13, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(37.63, 83.13, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(37.63, 83.13, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(40.91, 84.04, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(40.56, 85.45, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(40.56, 85.45, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(40.18, 85.14, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(40.18, 85.14, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(40.21, 86.82, "Thaldraszus", "Magmatalon", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(40.18, 85.15, "Thaldraszus", "Guardian Velomir", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(40.18, 85.15, "Thaldraszus", "Guardian Velomir", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(56.12, 40.28, "Valdrakken", "Captain Drine", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.32, 39.4, "Valdrakken", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.46, 78.92, "Thaldraszus", "Chromie", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.46, 78.95, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.5, 78.8, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(55.72, 77.3, "Thaldraszus", "Henlare", "Kill", "QUEST_WATCH_UPDATE")); -- LEVEL 70 ?
table.insert(steps, CreateStep(55, 75.64, "Thaldraszus", "Siaszerathel", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(54.97, 75.66, "Thaldraszus", "Siaszerathel", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(54.97, 75.66, "Thaldraszus", "Siaszerathel", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(53.2, 77.36, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(52.72, 76.85, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(52.72, 76.84, "Thaldraszus", "Crazed Alpha", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(54.96, 75.66, "Thaldraszus", "Siaszerathel", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(54.96, 75.66, "Thaldraszus", "Siaszerathel", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(54.96, 75.66, "Thaldraszus", "Siaszerathel", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.44, 78.9, "Thaldraszus", "Siaszerathel", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.44, 78.9, "Thaldraszus", "Siaszerathel", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.5, 78.8, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.6, 78.32, "Thaldraszus", "Andantenormu", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.5, 78.82, "Thaldraszus", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.5, 78.82, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.47, 78.9, "Thaldraszus", "Siaszerathel", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.55, 78.22, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.8, 79.31, "Thaldraszus", "Siaszerathel", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60, 79.25, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.97, 77.25, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.94, 77.25, "Thaldraszus", "Aeonormu", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.45, 78.92, "Thaldraszus", "Eloh", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.53, 78.79, "Thaldraszus", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.53, 78.79, "Thaldraszus", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.55, 78.85, "Thaldraszus", "Aeonormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(57.53, 78.86, "Thaldraszus", "Aeonormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.52, 78.81, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.56, 82.63, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.36, 82.18, "Thaldraszus", "Historian Jum'Flitmo", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(58.15, 82.85, "Thaldraszus", nil, "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(57.53, 78.86, "Thaldraszus", "Aeonormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(57.52, 78.81, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.6, 81.75, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.56, 82.63, "Thaldraszus", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.36, 82.18, "Thaldraszus", "Historian Jum'Flitmo", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(58.15, 82.85, "Thaldraszus", "Time-Lost Sunseeker", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.49, 79.78, "Thaldraszus", "Wan'she Skystrider", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.58, 82.63, "Thaldraszus", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.67, 81.67, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.64, 81.68, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.57, 81.85, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.51, 83.27, "Thaldraszus", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.64, 83.69, "Thaldraszus", "Colossal Causality", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.64, 81.84, "Thaldraszus", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.64, 81.84, "Thaldraszus", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.64, 81.84, "Thaldraszus", "Chromie", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.05, 82.45, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.05, 82.45, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.53, 82.49, "Thaldraszus", "Soridormi", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.31, 82.18, "Thaldraszus", "Siaszerathel", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.17, 81.77, "Thaldraszus", "Andantenormu", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.06, 82.44, "Thaldraszus", "Nozdormu", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.09, 82.43, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.09, 82.43, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.09, 82.43, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.19, 51, "The Primalist Future", "Soridormi", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.19, 51, "The Primalist Future", "Soridormi", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.41, 50.33, "The Primalist Future", "Soridormi", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(38.96, 24.12, "The Primalist Future", "Restless Icicle", "Kill", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(47.22, 41.96, "The Primalist Future", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(61.36, 50.9, "The Primalist Future", "Soridormi", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.49, 50.34, "The Primalist Future", "Soridormi", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.29, 50.7, "The Primalist Future", "Soridormi", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.08, 82.46, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.08, 82.46, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.86, 66.22, "Azmerloth", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.86, 66.22, "Azmerloth", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.94, 66.08, "Azmerloth", "Thrallgrulgulgul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(61.84, 61.99, "Azmerloth", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.86, 66.16, "Azmerloth", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60, 66.05, "Azmerloth", "Thrallgrulgulgul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.95, 66.1, "Azmerloth", "Thrallgrulgulgul", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(59.83, 65.76, "Azmerloth", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(59.98, 65.91, "Azmerloth", "Thrallgrulgulgul", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(59.85, 66.11, "Azmerloth", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(60.06, 82.47, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.06, 82.47, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.06, 82.47, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(43.45, 69.14, "The Gnoll War", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(43.47, 69.21, "The Gnoll War", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(52.48, 74.27, "The Black Empire", "Andantenormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(52.47, 74, "The Black Empire", "Andantenormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(53.57, 43.36, "The Black Empire", nil, "Click", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(53.05, 43.76, "The Black Empire", "Chromie", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(53.08, 43.85, "The Black Empire", "Chromie", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(52.98, 44.03, "The Black Empire", "Chromie", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.09, 82.45, "Thaldraszus", "Chromie", "Talk", "QUEST_WATCH_UPDATE"));
table.insert(steps, CreateStep(60.07, 82.47, "Thaldraszus", "Nozdormu", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(60.07, 82.47, "Thaldraszus", "Nozdormu", "Accept quest", "QUEST_ACCEPTED"));
table.insert(steps, CreateStep(58.12, 35.88, "Valdrakken", "Alexstrasza the Life-Binder", "Turn in quest", "QUEST_TURNED_IN"));
table.insert(steps, CreateStep(61.53, 36.35, "Valdrakken", "ENDED", "COMPLETED", ""));
